version: 1
services:
  - name: insanely-fast-whisper-api
    type: web
    runtime: python
    branch: main
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
